# Generated by Django 2.1 on 2018-10-09 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='clone_for_flats',
        ),
    ]
