# Generated by Django 2.1 on 2018-10-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0002_remove_flat_clone_for_flats'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='schema',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
