# Generated by Django 2.1 on 2018-10-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0003_flat_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='schema',
            field=models.ImageField(upload_to='flats'),
        ),
    ]
